/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Address = IDL.Record({
  'tag' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'state' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RestaurantId = IDL.Nat;
export const MenuItemInput = IDL.Record({
  'imageBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'restaurantId' : RestaurantId,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const MenuItemId = IDL.Nat;
export const RestaurantInput = IDL.Record({
  'imageBlob' : IDL.Opt(ExternalBlob),
  'deliveryFee' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deliveryTimeMinutes' : IDL.Nat,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});
export const AddReviewInput = IDL.Record({
  'userName' : IDL.Text,
  'restaurantId' : RestaurantId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const AddToCartInput = IDL.Record({
  'name' : IDL.Text,
  'restaurantId' : RestaurantId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'savedAddresses' : IDL.Vec(Address),
  'email' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'phone' : IDL.Text,
});
export const UserId = IDL.Principal;
export const CartItem = IDL.Record({
  'name' : IDL.Text,
  'restaurantId' : RestaurantId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const Cart = IDL.Record({
  'userId' : UserId,
  'items' : IDL.Vec(CartItem),
});
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'restaurantId' : RestaurantId,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Placed' : IDL.Null,
  'Preparing' : IDL.Null,
  'Cancelled' : IDL.Null,
  'OutForDelivery' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'tax' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'total' : IDL.Nat,
  'deliveryFee' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'restaurantId' : RestaurantId,
  'updatedAt' : Timestamp,
  'specialInstructions' : IDL.Text,
  'restaurantName' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const Restaurant = IDL.Record({
  'id' : RestaurantId,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'deliveryFee' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'deliveryTimeMinutes' : IDL.Nat,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'reviewCount' : IDL.Nat,
});
export const RestaurantRatingSummary = IDL.Record({
  'restaurantId' : RestaurantId,
  'averageRating' : IDL.Float64,
  'reviewCount' : IDL.Nat,
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'userName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'restaurantId' : RestaurantId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const PlaceOrderInput = IDL.Record({
  'tax' : IDL.Nat,
  'deliveryAddress' : IDL.Text,
  'total' : IDL.Nat,
  'deliveryFee' : IDL.Nat,
  'restaurantId' : RestaurantId,
  'specialInstructions' : IDL.Text,
  'restaurantName' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const UserProfileInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const RestaurantFilter = IDL.Record({
  'minRating' : IDL.Opt(IDL.Float64),
  'searchTerm' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addDeliveryAddress' : IDL.Func([Address], [], []),
  'addMenuItem' : IDL.Func([MenuItemInput], [MenuItemId], []),
  'addRestaurant' : IDL.Func([RestaurantInput], [RestaurantId], []),
  'addReview' : IDL.Func([AddReviewInput], [ReviewId], []),
  'addToCart' : IDL.Func([AddToCartInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
  'deleteRestaurant' : IDL.Func([RestaurantId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getRestaurant' : IDL.Func([RestaurantId], [IDL.Opt(Restaurant)], ['query']),
  'getRestaurantRatingSummary' : IDL.Func(
      [RestaurantId],
      [RestaurantRatingSummary],
      ['query'],
    ),
  'getRestaurantReviews' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
  'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'listUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderInput], [OrderId], []),
  'removeDeliveryAddress' : IDL.Func([IDL.Nat], [], []),
  'removeFromCart' : IDL.Func([MenuItemId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
  'searchRestaurants' : IDL.Func(
      [RestaurantFilter],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
  'seedData' : IDL.Func([], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleRestaurantStatus' : IDL.Func([RestaurantId], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCartItem' : IDL.Func([MenuItemId, IDL.Nat], [], []),
  'updateMenuItem' : IDL.Func([MenuItemId, MenuItemInput], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateRestaurant' : IDL.Func([RestaurantId, RestaurantInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Address = IDL.Record({
    'tag' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'state' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RestaurantId = IDL.Nat;
  const MenuItemInput = IDL.Record({
    'imageBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'restaurantId' : RestaurantId,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const MenuItemId = IDL.Nat;
  const RestaurantInput = IDL.Record({
    'imageBlob' : IDL.Opt(ExternalBlob),
    'deliveryFee' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deliveryTimeMinutes' : IDL.Nat,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AddReviewInput = IDL.Record({
    'userName' : IDL.Text,
    'restaurantId' : RestaurantId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const AddToCartInput = IDL.Record({
    'name' : IDL.Text,
    'restaurantId' : RestaurantId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'savedAddresses' : IDL.Vec(Address),
    'email' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const CartItem = IDL.Record({
    'name' : IDL.Text,
    'restaurantId' : RestaurantId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const Cart = IDL.Record({ 'userId' : UserId, 'items' : IDL.Vec(CartItem) });
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'restaurantId' : RestaurantId,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Placed' : IDL.Null,
    'Preparing' : IDL.Null,
    'Cancelled' : IDL.Null,
    'OutForDelivery' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'tax' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'total' : IDL.Nat,
    'deliveryFee' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'restaurantId' : RestaurantId,
    'updatedAt' : Timestamp,
    'specialInstructions' : IDL.Text,
    'restaurantName' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const Restaurant = IDL.Record({
    'id' : RestaurantId,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'deliveryFee' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'deliveryTimeMinutes' : IDL.Nat,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'reviewCount' : IDL.Nat,
  });
  const RestaurantRatingSummary = IDL.Record({
    'restaurantId' : RestaurantId,
    'averageRating' : IDL.Float64,
    'reviewCount' : IDL.Nat,
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'userName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'restaurantId' : RestaurantId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const PlaceOrderInput = IDL.Record({
    'tax' : IDL.Nat,
    'deliveryAddress' : IDL.Text,
    'total' : IDL.Nat,
    'deliveryFee' : IDL.Nat,
    'restaurantId' : RestaurantId,
    'specialInstructions' : IDL.Text,
    'restaurantName' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const UserProfileInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RestaurantFilter = IDL.Record({
    'minRating' : IDL.Opt(IDL.Float64),
    'searchTerm' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addDeliveryAddress' : IDL.Func([Address], [], []),
    'addMenuItem' : IDL.Func([MenuItemInput], [MenuItemId], []),
    'addRestaurant' : IDL.Func([RestaurantInput], [RestaurantId], []),
    'addReview' : IDL.Func([AddReviewInput], [ReviewId], []),
    'addToCart' : IDL.Func([AddToCartInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
    'deleteRestaurant' : IDL.Func([RestaurantId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(Restaurant)],
        ['query'],
      ),
    'getRestaurantRatingSummary' : IDL.Func(
        [RestaurantId],
        [RestaurantRatingSummary],
        ['query'],
      ),
    'getRestaurantReviews' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
    'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'listUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderInput], [OrderId], []),
    'removeDeliveryAddress' : IDL.Func([IDL.Nat], [], []),
    'removeFromCart' : IDL.Func([MenuItemId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
    'searchRestaurants' : IDL.Func(
        [RestaurantFilter],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'seedData' : IDL.Func([], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleRestaurantStatus' : IDL.Func([RestaurantId], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCartItem' : IDL.Func([MenuItemId, IDL.Nat], [], []),
    'updateMenuItem' : IDL.Func([MenuItemId, MenuItemInput], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateRestaurant' : IDL.Func([RestaurantId, RestaurantInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };