/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddReviewInput {
  'userName' : string,
  'restaurantId' : RestaurantId,
  'comment' : string,
  'rating' : bigint,
}
export interface AddToCartInput {
  'name' : string,
  'restaurantId' : RestaurantId,
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : MenuItemId,
}
export interface Address {
  'tag' : string,
  'street' : string,
  'city' : string,
  'postalCode' : string,
  'state' : string,
}
export interface Cart { 'userId' : UserId, 'items' : Array<CartItem> }
export interface CartItem {
  'name' : string,
  'restaurantId' : RestaurantId,
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : MenuItemId,
}
export type ExternalBlob = Uint8Array;
export interface MenuItem {
  'id' : MenuItemId,
  'imageBlob' : [] | [ExternalBlob],
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'restaurantId' : RestaurantId,
  'category' : string,
  'price' : bigint,
}
export type MenuItemId = bigint;
export interface MenuItemInput {
  'imageBlob' : [] | [ExternalBlob],
  'name' : string,
  'description' : string,
  'restaurantId' : RestaurantId,
  'category' : string,
  'price' : bigint,
}
export interface Order {
  'id' : OrderId,
  'tax' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'total' : bigint,
  'deliveryFee' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'restaurantId' : RestaurantId,
  'updatedAt' : Timestamp,
  'specialInstructions' : string,
  'restaurantName' : string,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : MenuItemId,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Placed' : null } |
  { 'Preparing' : null } |
  { 'Cancelled' : null } |
  { 'OutForDelivery' : null };
export interface PlaceOrderInput {
  'tax' : bigint,
  'deliveryAddress' : string,
  'total' : bigint,
  'deliveryFee' : bigint,
  'restaurantId' : RestaurantId,
  'specialInstructions' : string,
  'restaurantName' : string,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface Restaurant {
  'id' : RestaurantId,
  'imageBlob' : [] | [ExternalBlob],
  'deliveryFee' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'deliveryTimeMinutes' : bigint,
  'address' : string,
  'category' : string,
  'rating' : number,
  'phone' : string,
  'reviewCount' : bigint,
}
export interface RestaurantFilter {
  'minRating' : [] | [number],
  'searchTerm' : [] | [string],
  'category' : [] | [string],
}
export type RestaurantId = bigint;
export interface RestaurantInput {
  'imageBlob' : [] | [ExternalBlob],
  'deliveryFee' : bigint,
  'name' : string,
  'description' : string,
  'deliveryTimeMinutes' : bigint,
  'address' : string,
  'category' : string,
  'phone' : string,
}
export interface RestaurantRatingSummary {
  'restaurantId' : RestaurantId,
  'averageRating' : number,
  'reviewCount' : bigint,
}
export interface Review {
  'id' : ReviewId,
  'userName' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'restaurantId' : RestaurantId,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'createdAt' : Timestamp,
  'savedAddresses' : Array<Address>,
  'email' : string,
  'isAdmin' : boolean,
  'phone' : string,
}
export interface UserProfileInput {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addDeliveryAddress' : ActorMethod<[Address], undefined>,
  'addMenuItem' : ActorMethod<[MenuItemInput], MenuItemId>,
  'addRestaurant' : ActorMethod<[RestaurantInput], RestaurantId>,
  'addReview' : ActorMethod<[AddReviewInput], ReviewId>,
  'addToCart' : ActorMethod<[AddToCartInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteMenuItem' : ActorMethod<[MenuItemId], undefined>,
  'deleteRestaurant' : ActorMethod<[RestaurantId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getMenuItem' : ActorMethod<[MenuItemId], [] | [MenuItem]>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [Restaurant]>,
  'getRestaurantRatingSummary' : ActorMethod<
    [RestaurantId],
    RestaurantRatingSummary
  >,
  'getRestaurantReviews' : ActorMethod<[RestaurantId], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listMenuItems' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'listRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'listUserOrders' : ActorMethod<[], Array<Order>>,
  'placeOrder' : ActorMethod<[PlaceOrderInput], OrderId>,
  'removeDeliveryAddress' : ActorMethod<[bigint], undefined>,
  'removeFromCart' : ActorMethod<[MenuItemId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'searchRestaurants' : ActorMethod<[RestaurantFilter], Array<Restaurant>>,
  'seedData' : ActorMethod<[], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleRestaurantStatus' : ActorMethod<[RestaurantId], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCartItem' : ActorMethod<[MenuItemId, bigint], undefined>,
  'updateMenuItem' : ActorMethod<[MenuItemId, MenuItemInput], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateRestaurant' : ActorMethod<[RestaurantId, RestaurantInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];